-- Ejecutar antes de iniciar el catálogo. No reactiva registros existentes.
USE CATALOGO_P3_DB;
GO
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF COL_LENGTH('dbo.ARTICULOS', 'Activo') IS NULL
    ALTER TABLE dbo.ARTICULOS ADD Activo BIT NOT NULL CONSTRAINT DF_ARTICULOS_Activo DEFAULT (1) WITH VALUES;
IF COL_LENGTH('dbo.MARCAS', 'Activo') IS NULL
    ALTER TABLE dbo.MARCAS ADD Activo BIT NOT NULL CONSTRAINT DF_MARCAS_Activo DEFAULT (1) WITH VALUES;
IF COL_LENGTH('dbo.CATEGORIAS', 'Activo') IS NULL
    ALTER TABLE dbo.CATEGORIAS ADD Activo BIT NOT NULL CONSTRAINT DF_CATEGORIAS_Activo DEFAULT (1) WITH VALUES;
COMMIT TRANSACTION;
GO
